#!/bin/sh

install_zsh() {
    # installing oh-my-zsh
    if [ ! -d $HOME/.oh-my-zsh ]; then
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi

    if [ ! -L $HOME/.zshrc ]; then
        rm $HOME/.zshrc
    fi
    if [ ! -L $HOME/.alias ]; then
        rm $HOME/.alias
    fi
    if [ ! -L $HOME/.exports ]; then
        rm $HOME/.exports
    fi
    stow -R -t $HOME zsh
}

install_nvim() {
    if [ ! -f $HOME/.local/share/nvim/site/autoload/plug.vim ]; then
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
    if [ ! -L $HOME/.config/nvim/init.vim ]; then
        rm $HOME/.config/nvim/init.vim
    fi
    stow -R -t $HOME nvim
}

install_tmux() {
    if [ ! -L $HOME/.tmux.conf ]; then
        rm $HOME/.tmux.conf
    fi
    stow -R -t $HOME tmux
}

install_bin() {
    stow -R -t $HOME bin
}

install_alactritty() {
    if [ ! -L $HOME/.config/alacritty/alacritty.yml ]; then
        rm -rf $HOME/.config/alacritty
    fi

    if [ ! -L $HOME/.config/alacritty/theme ];then
        rm -rf $HOME/.config/alacritty/theme
    fi

    stow -R -t $HOME alacritty
}

install_bash() {
    if [ ! -L $HOME/.bashrc ]; then
        mv $HOME/.bashrc $HOME/.bashrc.backup
    fi

    stow -R -t $HOME bash
}

install_micro() {
    if [ ! -L $HOME/.config/micro/settings.json ]; then
        rm -f $HOME/.config/micro/settings.json
    fi
    stow -R -t $HOME micro
}

install_spacemacs() {
    if [ ! -L $HOME/.spacemacs ]; then
        rm -f $HOME/.spacemacs
    fi
    stow -R -t $HOME spacemacs
}

install_vim() {
    if [ ! -L $HOME/.vimrc ]; then
        rm -f $HOME/.vimrc
    fi
    stow -R -t $HOME vimrc
}

install_clang_format() {
    if [ ! -L $HOME/.clang-format ]; then
        rm -f $HOME/.clang-format
    fi
    stow -R -t $HOME clangformat
}

install_sublime() {
    if [ ! -L $HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings ]; then
        rm -r $HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    fi
    stow -R -t $HOME sublimetext
}

install_kitty() {
    if [ ! -L $HOME/.config/kitty/kitty.conf ]; then
        rm -rf $HOME/.config/kitty
    fi

    stow -R -t $HOME kitty 
}

install_i3() {
    if [ ! -L $HOME/.config/i3/config ]; then
        rm -f $HOME/.config/i3/config
    fi
    stow -R -t $HOME i3
}

install_vscodium() {
    if [ ! -L $HOME/.config/VSCodium/User/settings.json ]; then
        rm -r $HOME/.config/VSCodium/User/settings.json
    fi
    stow -R -t $HOME vscodium
}

install_vscode() {
    if [ ! -L $HOME/.config/Code/User/settings.json ]; then
        rm -r $HOME/.config/Code/User/settings.json
    fi
    stow -R -t $HOME vscode
}

install_gnome() {
    if [ ! -L $HOME/.config/gtk-3.0/gtk.css ]; then
        rm -r $HOME/.config/gtk-3.0/gtk.css
    fi
    stow -R -t $HOME gnome
}

install_fish() {
    if [ ! -L $HOME/.config/fish/config.fish ]; then
        rm -r $HOME/.config/fish/config.fish
    fi

    stow -R -t $HOME fish
}

install_zsh
install_nvim
install_tmux
install_bin
install_alactritty
install_bash
install_micro
install_vim
install_clang_format
install_kitty
install_i3
install_gnome
install_fish
