#!/bin/sh

install_zsh() {
    # installing oh-my-zsh
    if [ ! -d $HOME/.oh-my-zsh ]; then
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi

    if [ ! -L $HOME/.zshrc ]; then
        rm $HOME/.zshrc
    fi
    if [ ! -L $HOME/.alias ]; then
        rm $HOME/.alias
    fi
    if [ ! -L $HOME/.exports ]; then
        rm $HOME/.exports
    fi
    stow -R -t $HOME zsh
}

install_nvim() {
    if [ ! -f $HOME/.local/share/nvim/site/autoload/plug.vim ]; then
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
    if [ ! -L $HOME/.config/nvim/init.vim ]; then
        rm $HOME/.config/nvim/init.vim
    fi
    stow -R -t $HOME nvim
}

install_tmux() {
    if [ ! -L $HOME/.tmux.conf ]; then
        rm $HOME/.tmux.conf
    fi
    stow -R -t $HOME tmux
}

install_bin() {
    stow -R -t $HOME bin
}

# install_alactritty() {
    # if [ ! -L $HOME/.config/alacritty/alacritty.yml ]; then
        # rm -rf $HOME/.config/alacritty
    # fi
# 
    # if [ ! -L $HOME/.config/alacritty/theme ];then
        # rm -rf $HOME/.config/alacritty/theme
    # fi
# 
    # stow -R -t $HOME alacritty
# }

install_bash() {
    if [ ! -L $HOME/.bashrc ]; then
        mv $HOME/.bashrc $HOME/.bashrc.backup
    fi

    if [ ! -L $HOME/.functions ]; then
    	rm $HOME/.functions
    fi

    stow -R -t $HOME bash
}

# install_spacemacs() {
    # if [ ! -L $HOME/.spacemacs ]; then
        # rm -rf $HOME/.spacemacs
    # fi
# 
    # stow -R -t $HOME spacemacs
# }
# 
install_micro() {
    # if [ ! -L $HOME/.config/micro/settings.json ]; then
        # rm -f $HOME/.config/micro/settings.json
    # fi
# 
	# if [ ! -L $HOME/.config/micro/bindings.json ]; then
		# rm -f $HOME/.config/micro/bindings.json
	# fi

    stow -R -t $HOME micro
}

install_vim() {
    if [ ! -L $HOME/.vimrc ]; then
        rm -f $HOME/.vimrc
    fi
    stow -R -t $HOME vimrc
}

install_clang_format() {
    if [ ! -L $HOME/.clang-format ]; then
        rm -f $HOME/.clang-format
    fi
    stow -R -t $HOME clangformat
}

install_i3() {
    if [ ! -L $HOME/.config/i3/config ]; then
        rm -f $HOME/.config/i3/config
    fi
    stow -R -t $HOME i3
}

install_user_

install_systemd_user() {
	stow -R -t $HOME systemd
}

git submodule update --init

install_zsh
install_nvim
install_tmux
install_bin
install_bash
install_micro
install_vim
install_clang_format
install_i3
install_systemd_user
